var myString;
var myNum;
var myBool;
var myvar;
var strArr;
var numArr;
// let boolArr: boolean[];
var boolArr;
var strNumTuple;
myString = "Hello World".slice(0, 3);
myNum = 5.5 + 5;
myBool = false;
strArr = ["hello", "world"];
numArr = [1, 2, 3];
strNumTuple = ['hello', 4];
var myVoid = undefined;
var myNull = null;
var myUndefined = null;
console.log(myNull);
